language: elixir
elixir:
    - 1.4.1
otp_release:
    - 19.2

sudo: required
services:
  - docker

before_install:
  - docker run -d -p 2197:2197 mobify/apns-http2-mock-server
  - docker run -d -p 443:443 roxeon/fcm-http2-mock-server

env:
    - MIX_ENV=test

script: mix coveralls.travis
